const defaultProperties = [
  'key',
  'type',
  'props.required',
  'props.label',
  'props.placeholder',
  'props.description',
  'hide',
  'props.disabled',
  'props.readonly',
];
const propertiesWithOptions = [
  'key',
  'type',
  'props.required',
  'props.label',
  'props.placeholder',
  'props.description',
  'hide',
  'props.disabled',
  'props.readonly',
  'props.options',
];
const propertiesArrayType = [
  'key',
  'type',
  'props.required',
  'props.label',
  'hide',
  'props.disabled',
  'props.readonly',
  'props.emptyArrayMessage',
  'props.addButtonLabel',
];
const propertiesActionType = [
  'key',
  'type',
  'props.inputGroups',
  'props.label',
  'props.url',
  'props.method',
  'props.responseType',
  'props.action',
  'hide',
  'props.disabled',
];

export const defaultPropertiesByType = {
  action: propertiesActionType,
  app: ['spacing', 'type', 'props.menu', 'props.pages'],
  'app-breadcrumb': ['key', 'type'],
  'app-navigation': ['key', 'type'],
  array: propertiesArrayType,
  boolean: defaultProperties,
  checkbox: defaultProperties,
  datepicker: defaultProperties,
  datetimepicker: defaultProperties,
  'dialog-button': ['key', 'type', 'props.label', 'props.form', 'hide'],
  enum: propertiesWithOptions,
  'error-message': defaultProperties,
  'formly-template': ['key', 'template'],
  grid: propertiesArrayType,
  input: defaultProperties,
  integer: defaultProperties,
  link: ['key', 'type', 'props.label', 'props.url', 'hide'],
  'load-action': propertiesActionType
    .map((i) => (i === 'props.action' ? 'spacing' : i))
    .concat(['props.autoRun']),
  'formly-group': ['key', 'type', 'hide', 'props.disabled'],
  message: defaultProperties,
  'message-container': ['spacing', 'type'],
  number: defaultProperties,
  multicheckbox: propertiesWithOptions,
  object: [
    'key',
    'type',
    'props.required',
    'props.label',
    'hide',
    'props.disabled',
    'props.readonly',
  ],
  page: ['props.navigationDisabled', 'type'],
  'save-action': propertiesActionType.map((i) =>
    i === 'props.action' ? 'spacing' : i,
  ),
  radio: propertiesWithOptions,
  select: propertiesWithOptions,
  string: defaultProperties,
  textarea: defaultProperties.slice().concat(['props.rows']),
  'url-select': [
    'key',
    'type',
    'props.required',
    'props.label',
    'props.placeholder',
    'props.description',
    'hide',
    'props.disabled',
    'props.readonly',
    'props.url',
    'props.valueKey',
    'props.labelKey',
  ],
};
